/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dndpocketknife;

/**
 *
 * @author timbl
 */
public class GUI extends javax.swing.JFrame {
    private final dCustom D20 = new dCustom(1,20);
    private final dCustom D12 = new dCustom(1,12);
    private final dCustom D00 = new dCustom(0,9,10);
    private final dCustom D10 = new dCustom(1,10);
    private final dCustom D8 = new dCustom(1,8);
    private final dCustom D6 = new dCustom(1,6);
    private final dCustom D4 = new dCustom(1,4);
    /**
     * Creates new form Test
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        rollButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        diceList = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        diceSelector = new javax.swing.JComboBox<>();
        diceNumber = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        d4Button = new javax.swing.JButton();
        d6Button = new javax.swing.JButton();
        d8Button = new javax.swing.JButton();
        d10Button = new javax.swing.JButton();
        d00Button = new javax.swing.JButton();
        d12Button = new javax.swing.JButton();
        d20Button = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        rollResultsPane = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel4.add(addButton);

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel4.add(removeButton);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        rollButton.setText("ROLL");
        jPanel3.add(rollButton, java.awt.BorderLayout.PAGE_END);

        diceList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(diceList);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dice Select:");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel10.setLayout(new java.awt.GridLayout(1, 2));

        diceSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "d4", "d6", "d8", "d10", "d00", "d12", "d20" }));
        diceSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceSelectorActionPerformed(evt);
            }
        });
        jPanel10.add(diceSelector);
        jPanel10.add(diceNumber);

        jPanel5.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Preset Dice");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new java.awt.GridLayout(7, 1));

        d4Button.setText("d4");
        d4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d4Button);

        d6Button.setText("d6");
        d6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d6Button);

        d8Button.setText("d8");
        d8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d8Button);

        d10Button.setText("d10");
        d10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d10Button);

        d00Button.setText("d00");
        d00Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d00Button);

        d12Button.setText("d12");
        d12Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d12Button);

        d20Button.setText("d20");
        d20Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d20Button);

        jPanel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel6, java.awt.BorderLayout.EAST);

        jPanel9.setPreferredSize(new java.awt.Dimension(300, 375));
        jPanel9.setLayout(new java.awt.BorderLayout());

        rollResultsPane.setColumns(20);
        rollResultsPane.setRows(5);
        scrollPanel.setViewportView(rollResultsPane);

        jPanel9.add(scrollPanel, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Dice Roller", jPanel1);
        jTabbedPane1.addTab("tab2", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diceSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diceSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diceSelectorActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeButtonActionPerformed

    private void diceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diceButtonActionPerformed
        javax.swing.JButton source = (javax.swing.JButton) evt.getSource();
        if(source == d4Button){
            D4.roll();
            rollResultsPane.append("\r\n"+D4.toString());
        }
        else if(source == d6Button){
            D6.roll();
            rollResultsPane.append("\r\n"+D6.toString());
        }
        else if(source == d8Button){
            D8.roll();
            rollResultsPane.append("\r\n"+D8.toString());
        }
        else if(source == d10Button){
            D10.roll();
            rollResultsPane.append("\r\n"+D10.toString());
        }
        else if(source == d00Button){
            D00.roll();
            rollResultsPane.append("\r\n"+D00.toString());
        }
        else if(source == d12Button){
            D12.roll();
            rollResultsPane.append("\r\n"+D12.toString());
        }
        else if(source == d20Button){
            D20.roll();
            rollResultsPane.append("\r\n"+D20.toString());
        }
        else{
            System.out.println("Error: dice button mismatch");
            throw new IllegalStateException();
        }
        //dice.roll();
        //rollResultsPane.append("\r\n"+dice.toString());
    }//GEN-LAST:event_diceButtonActionPerformed

    /*private void diceButtonActionPerformed(java.awt.event.ActionEvent evt){
        Die dice = (Die) evt.getSource();
        dice.roll();
        rollResultsPane.append(String.valueOf(dice.getValue())+"\r\n");
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton d00Button;
    private javax.swing.JButton d10Button;
    private javax.swing.JButton d12Button;
    private javax.swing.JButton d20Button;
    private javax.swing.JButton d4Button;
    private javax.swing.JButton d6Button;
    private javax.swing.JButton d8Button;
    private javax.swing.JList<String> diceList;
    private javax.swing.JSpinner diceNumber;
    private javax.swing.JComboBox<String> diceSelector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton rollButton;
    private javax.swing.JTextArea rollResultsPane;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
