/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dndpocketknife;

import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author timbl
 */
public class GUI extends javax.swing.JFrame {
    //initialising all the preset real world dice using instances of the dCustom class
    private final dCustom D20 = new dCustom(1,20);
    private final dCustom D12 = new dCustom(1,12);
    private final dCustom D00 = new dCustom("d00",0,9,10);
    private final dCustom D10 = new dCustom(1,10);
    private final dCustom D8 = new dCustom(1,8);
    private final dCustom D6 = new dCustom(1,6);
    private final dCustom D4 = new dCustom(1,4);
    private DefaultListModel diceListModel;
    private Die[] data;
    /**
     * Creates new form Test
     */
    public GUI() {
        data = new Die[]{new dCustom(1,20), new dCustom(1,6), new dCustom("Coin", 0, 1)};
        diceListModel = new DefaultListModel();
        for(int i=0; i<data.length; i++){
            diceListModel.addElement(data[i]);
        }
        initComponents();
        diceList.setCellRenderer(new dieCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        dicePanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        rollButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        diceList = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        diceSelectLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        diceSelector = new javax.swing.JComboBox<>();
        diceNumber = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        presetDiceLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        d4Button = new javax.swing.JButton();
        d6Button = new javax.swing.JButton();
        d8Button = new javax.swing.JButton();
        d10Button = new javax.swing.JButton();
        d00Button = new javax.swing.JButton();
        d12Button = new javax.swing.JButton();
        d20Button = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        rollResultsPane = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dicePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dicePanel.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel4.add(addButton);

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel4.add(removeButton);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        rollButton.setText("ROLL");
        jPanel3.add(rollButton, java.awt.BorderLayout.PAGE_END);

        diceList.setModel(diceListModel);
        diceList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        diceList.setToolTipText("");
        diceList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        diceList.setEnabled(false);
        jScrollPane1.setViewportView(diceList);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.BorderLayout());

        diceSelectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diceSelectLabel.setText("Dice Select:");
        diceSelectLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(diceSelectLabel, java.awt.BorderLayout.PAGE_START);

        jPanel10.setLayout(new java.awt.GridLayout(1, 2));

        diceSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "d4", "d6", "d8", "d10", "d00", "d12", "d20" }));
        diceSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceSelectorActionPerformed(evt);
            }
        });
        jPanel10.add(diceSelector);
        jPanel10.add(diceNumber);

        jPanel5.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new java.awt.BorderLayout());

        presetDiceLabel.setText("Preset Dice");
        presetDiceLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(presetDiceLabel, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new java.awt.GridLayout(7, 1));

        d4Button.setText("d4");
        d4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d4Button);

        d6Button.setText("d6");
        d6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d6Button);

        d8Button.setText("d8");
        d8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d8Button);

        d10Button.setText("d10");
        d10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d10Button);

        d00Button.setText("d00");
        d00Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d00Button);

        d12Button.setText("d12");
        d12Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d12Button);

        d20Button.setText("d20");
        d20Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceButtonActionPerformed(evt);
            }
        });
        jPanel8.add(d20Button);

        jPanel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7, java.awt.BorderLayout.EAST);

        dicePanel.add(jPanel6, java.awt.BorderLayout.EAST);

        jPanel9.setPreferredSize(new java.awt.Dimension(300, 375));
        jPanel9.setLayout(new java.awt.BorderLayout());

        rollResultsPane.setColumns(20);
        rollResultsPane.setRows(5);
        scrollPanel.setViewportView(rollResultsPane);

        jPanel9.add(scrollPanel, java.awt.BorderLayout.CENTER);

        dicePanel.add(jPanel9, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Dice Roller", dicePanel);
        jTabbedPane1.addTab("tab2", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diceSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diceSelectorActionPerformed
        //Each item should correspond to a particular dice, or a custom dice where a dialog opens and requests the relevent parameters
    }//GEN-LAST:event_diceSelectorActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //Button functionality should add selected dice from diceSelector and add it to diceList
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        //Should remove selected diceList item from diceList
    }//GEN-LAST:event_removeButtonActionPerformed

    private void diceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diceButtonActionPerformed
        //Based on which button is pressed, selects dice, rolls, and announces name and result to rollResultsPane
        javax.swing.JButton source = (javax.swing.JButton) evt.getSource();
        Die dice = null;
        if(source == d4Button){
            dice = D4;
        }
        else if(source == d6Button){
            dice = D6;
        }
        else if(source == d8Button){
            dice = D8;
        }
        else if(source == d10Button){
            dice = D10;
        }
        else if(source == d00Button){
            dice = D00;
        }
        else if(source == d12Button){
            dice = D12;
        }
        else if(source == d20Button){
            dice = D20;
        }
        else{
            System.out.println("Error: dice button mismatch");
            throw new IllegalStateException();
        }
        dice.roll();
        rollResultsPane.append(dice.toString()+"\r\n");
    }//GEN-LAST:event_diceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton d00Button;
    private javax.swing.JButton d10Button;
    private javax.swing.JButton d12Button;
    private javax.swing.JButton d20Button;
    private javax.swing.JButton d4Button;
    private javax.swing.JButton d6Button;
    private javax.swing.JButton d8Button;
    private javax.swing.JList<Object> diceList;
    private javax.swing.JSpinner diceNumber;
    private javax.swing.JPanel dicePanel;
    private javax.swing.JLabel diceSelectLabel;
    private javax.swing.JComboBox<String> diceSelector;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel presetDiceLabel;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton rollButton;
    private javax.swing.JTextArea rollResultsPane;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
